name: rubocop_plugin_render
version: 0.0.1
language: ruby 
description: Render for rubocop result
tags:
 - ruby
 - rubocop
 - format
 - result
 - analyzer
 - plugin

public: true

# clone_in_docker: false

inputs:
  - name: FLOW_RUBOCOP_LOG_PATH
    editable: true

  - name: FLOW_PROJECT_ID
    editable: false


outputs:
  - name: FLOW_RUBOCOP_RENDER_URL

script_path: ./run.sh

template: |
  <div style="position: relative;height: 500px;">
    <a href="${FLOW_RUBOCOP_RENDER_URL}" style="position: absolute;top: 12px;right: 12px;z-index: 10;display: block; padding: 8px 14px; background: #81BF15; color: #fff;" target="_blank">Expand</a>
    <iframe style="width: 100%;border: none;height: 100%;" src="${FLOW_RUBOCOP_RENDER_URL}"></iframe>
  </div>